services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=donation_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - "0.0.0.0:5439:5432"
