services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=donation_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - "0.0.0.0:5439:5432"

  backend:
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/donation_db'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
